# .pre-commit-config.yaml
repos:
  - repo: https://github.com/psf/black
    rev: 24.4.0 # Check https://github.com/psf/black/releases for latest
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0 # Check
    hooks:
      - id: flake8
        args:
          - --max-line-length=120
          - --select=E9,F63,F7,F82,F541
          - --show-source
          - --statistics

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args:
          - --profile
          - black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
